# Generated by Django 4.0.5 on 2022-07-04 12:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='pwh',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50, null=True)),
                ('guardian_father_name', models.CharField(blank=True, max_length=50, null=True)),
                ('mothers_name', models.CharField(blank=True, max_length=50, null=True)),
                ('dob', models.DateField(null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other'), ('ND', 'Not to Disclosed')], max_length=50, null=True)),
                ('religion', models.CharField(blank=True, choices=[('H', 'Hindu'), ('M', 'Muslim'), ('C', 'Christian'), ('S', 'Sikh'), ('P', 'Parsi')], max_length=50, null=True)),
                ('caste', models.CharField(blank=True, choices=[('SC', 'SC'), ('ST', 'ST'), ('OBC', 'OBC'), ('G', 'General'), ('BC', 'BC'), ('FC', 'FC')], max_length=50, null=True)),
                ('tag', models.CharField(blank=True, choices=[('Deceased', 'Deceased'), ('Transfered', 'Transfered'), ('Blocked', 'Blocked'), ('Non PwH', 'Non PwH'), ('Not Our Member', 'Not Our Member'), ('Duplicate', 'Duplicate')], default='', max_length=20, null=True)),
                ('chapter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='useradress',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('line_1', models.CharField(max_length=255, null=True)),
                ('line_2', models.CharField(max_length=255, null=True)),
                ('line_3', models.CharField(max_length=255, null=True)),
                ('city', models.CharField(max_length=50, null=True)),
                ('tahsil', models.CharField(max_length=55, null=True)),
                ('district', models.CharField(max_length=55, null=True)),
                ('state', models.CharField(max_length=30, null=True)),
                ('pincode', models.IntegerField(null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chapter_address', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='pwhadress',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('line_1', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='flat/door/block_no')),
                ('line_2', models.CharField(blank=True, max_length=255, null=True, verbose_name='premises/buildings/village')),
                ('line_3', models.CharField(blank=True, max_length=255, null=True, verbose_name='Road/state/po')),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('tahsil', models.CharField(blank=True, max_length=55, null=True)),
                ('district', models.CharField(blank=True, max_length=55, null=True)),
                ('state', models.CharField(blank=True, max_length=30, null=True)),
                ('zone', models.CharField(blank=True, choices=[('Rural', 'Rural'), ('Urban', 'Urban')], max_length=50, null=True)),
                ('pincode', models.IntegerField(blank=True, null=True)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pwh_address', to='myapp.pwh')),
            ],
        ),
        migrations.CreateModel(
            name='PatientImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='pwh/images')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pwh_images', to='myapp.pwh')),
            ],
        ),
        migrations.CreateModel(
            name='Occupational',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_studying', models.BooleanField(blank=True, null=True)),
                ('highest_class', models.CharField(blank=True, max_length=50, null=True)),
                ('is_employed', models.BooleanField(blank=True, null=True)),
                ('employement_type', models.CharField(blank=True, max_length=50, null=True)),
                ('is_reimbursed', models.BooleanField(blank=True, null=True)),
                ('emp_or_name', models.CharField(blank=True, max_length=50, null=True)),
                ('reimbursment_type', models.CharField(blank=True, max_length=50, null=True)),
                ('pwh', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pwh_occupation', to='myapp.pwh')),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('aadhar_member', models.CharField(blank=True, max_length=20, null=True)),
                ('aadhar_father', models.CharField(blank=True, max_length=20, null=True)),
                ('aadhar_mother', models.CharField(blank=True, max_length=20, null=True)),
                ('aadhar_spouce', models.CharField(blank=True, max_length=20, null=True)),
                ('pwh', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pwh_membership', to='myapp.pwh')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('age_of_diagnosis', models.CharField(blank=True, max_length=20, null=True)),
                ('hospital_diagnosis', models.CharField(blank=True, max_length=50, null=True)),
                ('blood_group_with_rh', models.CharField(blank=True, choices=[('O+', 'O +ve'), ('O-', 'O -ve'), ('A+', 'A +ve'), ('A-', 'A -ve'), ('B+', 'B +ve'), ('B-', 'B -ve'), ('AB+', 'AB +ve'), ('AB-', 'AB -ve')], max_length=20, null=True)),
                ('factor_def', models.CharField(blank=True, choices=[('1', '1 (I)'), ('2', '2 (II)'), ('3', '3 (III)'), ('4', '4 (FIV)'), ('5', '5 (FV)'), ('6', '6 (FVI)'), ('7', '7 (FVII)'), ('8', '8 (FVIII)'), ('9', '9 (FIX)'), ('10', '10 (FX)'), ('11', '11 (FXI)'), ('12', '12 (FXII)'), ('13', '13 (FXIII)')], max_length=20, null=True)),
                ('factor_level', models.CharField(blank=True, max_length=20, null=True)),
                ('others_def', models.CharField(blank=True, choices=[('VwD', 'Von Willebrand'), ('glanzmann', 'Glanzmann'), ('fibronogenemia', 'Fibronogenemia'), ('hypofibrogenemia', 'Hypofibrogenemia'), ('functional platelate dissorder', 'Functional Platelete Dissorder'), ('disfibronogenemia', 'Disfibronogenemia')], max_length=50, null=True)),
                ('is_deformity', models.BooleanField(blank=True, null=True)),
                ('is_inhibitor_pos', models.BooleanField(blank=True, null=True)),
                ('is_hiv_pos', models.BooleanField(blank=True, null=True)),
                ('is_hcv_pos', models.BooleanField(blank=True, null=True)),
                ('pwh', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pwh_medical', to='myapp.pwh')),
            ],
        ),
        migrations.CreateModel(
            name='FamilyDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('no_of_affected', models.IntegerField(blank=True, null=True)),
                ('affected_nhr_id', models.CharField(blank=True, max_length=20, null=True)),
                ('family_income', models.CharField(blank=True, max_length=20, null=True)),
                ('is_bpl', models.BooleanField(blank=True, null=True)),
                ('bpl_ref_no', models.CharField(blank=True, max_length=20, null=True)),
                ('pwh', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pwh_family', to='myapp.pwh')),
            ],
        ),
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mobile', models.IntegerField(blank=True, null=True)),
                ('alternate_mobile', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contact', to='myapp.pwh')),
            ],
        ),
    ]
