# Generated by Django 4.0.5 on 2023-01-05 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_pwh_useradress_pwhadress_patientimage_occupational_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientimage',
            name='image',
            field=models.ImageField(upload_to='pwh_images'),
        ),
    ]
